import { ref } from 'vue'
import { Lesson } from '@/types/lesson'

const lessons = ref<Lesson[]>([
  {
  id: 0,
  courseId: 0,
  title: 'Getting Started - Introduce Yourself & Find Your Starting Point',
  slug: 'getting-started-introduce-yourself-find-your-starting-point',
  thumbnail: '/images/thumbnails/lesson-1.jpg',
  updatedAt: '2025-08-01',
  level: 'basic',
  views: 0,
},
{
  id: 1,
  courseId: 0,
  title: 'Welcome to the Jazz Guitar School',
  slug: 'welcome-to-the-jazz-guitar-school',
  thumbnail: '/images/thumbnails/lesson-2.jpg',
  updatedAt: '2025-08-01',
  level: 'basic',
  views: 0,
},
{
  id: 2,
  courseId: 0,
  title: 'Dave Stryker: How I Got Started',
  slug: 'dave-stryker-how-i-got-started',
  thumbnail: '/images/thumbnails/lesson-3.jpg',
  updatedAt: '2025-08-01',
  level: 'basic',
  views: 0,
},
{
  id: 3,
  courseId: 0,
  title: 'Getting Started - Introduce Yourself & Find Your Starting Point',
  slug: 'getting-started-introduce-yourself-find-your-starting-point-intermediate',
  thumbnail: '/images/thumbnails/lesson-4.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 4,
  courseId: 0,
  title: 'Tips for Transcribing',
  slug: 'tips-for-transcribing',
  thumbnail: '/images/thumbnails/lesson-5.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 5,
  courseId: 0,
  title: 'Jam Session Etiquette',
  slug: 'jam-session-etiquette',
  thumbnail: '/images/thumbnails/lesson-6.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 6,
  courseId: 0,
  title: 'Getting Started - Introduce Yourself & Find Your Starting Point',
  slug: 'getting-started-introduce-yourself-find-your-starting-point-advanced',
  thumbnail: '/images/thumbnails/lesson-1.jpg',
  updatedAt: '2025-08-01',
  level: 'advanced',
  views: 0,
},
{
  id: 7,
  courseId: 0,
  title: '4 Bar Major 2-5-1 - Advanced Melodic Phrasing Ideas',
  slug: '4-bar-major-2-5-1-advanced-melodic-phrasing-ideas',
  thumbnail: '/images/thumbnails/lesson-2.jpg',
  updatedAt: '2025-08-01',
  level: 'advanced',
  views: 0,
},
{
  id: 8,
  courseId: 0,
  title: '4 Bar Minor 2-5-1 - Advanced Melodic Phrasing Ideas',
  slug: '4-bar-minor-2-5-1-advanced-melodic-phrasing-ideas',
  thumbnail: '/images/thumbnails/lesson-3.jpg',
  updatedAt: '2025-08-01',
  level: 'advanced',
  views: 0,
},
{
  id: 9,
  courseId: 0,
  title: 'The 5 Positions of the F minor Pentatonic Scale',
  slug: '5-positions-of-f-minor-pentatonic-scale',
  thumbnail: '/images/thumbnails/lesson-4.jpg',
  updatedAt: '2025-08-01',
  level: 'bonus',
  views: 0,
},
{
  id: 10,
  courseId: 0,
  title: '“Christmas Time is Here”',
  slug: 'christmas-time-is-here',
  thumbnail: '/images/thumbnails/lesson-5.jpg',
  updatedAt: '2025-08-01',
  level: 'bonus',
  views: 0,
},
{
  id: 11,
  courseId: 0,
  title: '"Mr. P.C." - Playing over Minor Blues',
  slug: 'mr-pc-playing-over-minor-blues',
  thumbnail: '/images/thumbnails/lesson-6.jpg',
  updatedAt: '2025-08-01',
  level: 'bonus',
  views: 0,
},

{
  id: 12,
  courseId: 1,
  title: 'Backward Rolls - Practice Exercises',
  slug: 'backward-rolls-practice-exercises',
  thumbnail: '/images/thumbnails/lesson-1.jpg',
  updatedAt: '2025-08-01',
  level: 'basic',
  views: 0,
},
{
  id: 13,
  courseId: 1,
  title: 'Backward Roll Study - “You Are My Sunshine” - Key of C',
  slug: 'backward-roll-study-you-are-my-sunshine-key-of-c',
  thumbnail: '/images/thumbnails/lesson-2.jpg',
  updatedAt: '2025-08-01',
  level: 'basic',
  views: 0,
},
{
  id: 14,
  courseId: 1,
  title: 'Getting Started - Introduction & Course Overview',
  slug: 'getting-started-introduction-course-overview',
  thumbnail: '/images/thumbnails/lesson-3.jpg',
  updatedAt: '2025-08-01',
  level: 'basic',
  views: 0,
},
{
  id: 15,
  courseId: 1,
  title: 'Introduction to Intermediate',
  slug: 'introduction-to-intermediate',
  thumbnail: '/images/thumbnails/lesson-4.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 16,
  courseId: 1,
  title: 'Essential Music Theory',
  slug: 'essential-music-theory',
  thumbnail: '/images/thumbnails/lesson-5.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 17,
  courseId: 1,
  title: 'Introduction to Diatonic Chord Study',
  slug: 'introduction-to-diatonic-chord-study',
  thumbnail: '/images/thumbnails/lesson-6.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 18,
  courseId: 1,
  title: 'Diatonic Chords: Root Position - Chord Shapes and Qualities',
  slug: 'diatonic-chords-root-position-chord-shapes-and-qualities',
  thumbnail: '/images/thumbnails/lesson-1.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 19,
  courseId: 1,
  title: 'Diatonic Chords: Root Position - Triads within the Position',
  slug: 'diatonic-chords-root-position-triads-within-the-position',
  thumbnail: '/images/thumbnails/lesson-2.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 20,
  courseId: 1,
  title: 'Diatonic Chords: Root Position - Sixths within the Position',
  slug: 'diatonic-chords-root-position-sixths-within-the-position',
  thumbnail: '/images/thumbnails/lesson-3.jpg',
  updatedAt: '2025-08-01',
  level: 'intermediate',
  views: 0,
},
{
  id: 21,
  courseId: 1,
  title: 'Introduction to Advanced',
  slug: 'introduction-to-advanced',
  thumbnail: '/images/thumbnails/lesson-4.jpg',
  updatedAt: '2025-08-01',
  level: 'advanced',
  views: 0,
},
{
  id: 22,
  courseId: 1,
  title: 'What Defines a Left Hand Position?',
  slug: 'what-defines-a-left-hand-position',
  thumbnail: '/images/thumbnails/lesson-5.jpg',
  updatedAt: '2025-08-01',
  level: 'advanced',
  views: 0,
},
{
  id: 23,
  courseId: 1,
  title: '4 Note Diatonic 7th Chord Voicings',
  slug: '4-note-diatonic-7th-chord-voicings',
  thumbnail: '/images/thumbnails/lesson-6.jpg',
  updatedAt: '2025-08-01',
  level: 'advanced',
  views: 0,
},
])

export function useLessons() {
  return { lessons }
}
